version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nifi:
    image: apache/nifi
    ports:  
      - 8080:8080
    volumes:
      - ./cacerts.jks:/opt/nifi/nifi-current/conf/cacerts.jks
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME = admin
      - SINGLE_USER_CREDENTIALS_PASSWORD = Welcome010101
      - NIFI_WEB_HTTP_PORT=8080
  nifi-registry:
    image: apache/nifi-registry:1.15.1
    ports:
      - "18080:18080"
